
name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install deps
        run: |
          pip install buildozer cython==0.29.33
          sudo apt-get update
          sudo apt-get install -y zip unzip libffi-dev libssl-dev
      - name: Accept Licenses
        run: |
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses || true
          sdkmanager "build-tools;37.0.0" "platforms;android-33" "platform-tools"
      - name: Build APK
        run: |
          mkdir -p ~/.android/licenses
          cp $ANDROID_HOME/licenses/* ~/.android/licenses/ || true
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Pixel11-Pro-APK
          path: bin/*.apk
